### ISSUE TITLE
descripcion de segmentos

### ISSUE THREAD

**Issue by manureta** [hernan-alperin/Segmentacion-CORE#14]
Hay que agregar a la descripción del segmento, ademas del desde y hasta que ya estaba hablado un pasando_por para acumular los domicilios intermedios...

**Comment by hernan-alperin** [comment]
cuál es la _descripción del segmento_ referida?

el desde y el hasta refieren a ids de listado?
el pasando_por refiere sólo a datos de lado, ccalle y ncalle con resto en Null?

una posible opción es una tabla/vista (?)
segmento_id, listado_id, 'desde'
segmento_id, listado_id, 'hasta'
segmento_id, listado_id, 'pasando por' (1)

y qué este ultimo (1) sea único para cada lado

**Comment by manureta** [comment]
la __descricpion del segmento__ es la requerida. Una tabla/vista con la descripción de cada segmento del radio.
Según lo que se ha estado trabajando, la cual es tomada por qgis y será tomada por la interfaz web.
El desde y hasta, eran un id del listado y una forma textual del domicilio (ccalle - cnombre nrocatastral como se venia haciendo).
Para agregar el pasando por, pueden ser dos campos uno con un accumulado de los ids de domidilio y uno textual que haga un resumen leible x humano de esos domicilios (si son todos los de un lado, poner lado completo con la referencia al lado)

**Comment by hernan-alperin** [comment]
- la parte de *leible x humano* es una de las cosas que no queda claro

- no recuerdo que *(ccalle - cnombre nrocatastral como se venia haciendo)* se venía haciendo

**Comment by manureta** [comment]
ppdddlllffrr | prov | depto | codloc | frac | radio | segmento | seg | descripcion 
Según: https://github.com/hernan-alperin/Segmentacion-CORE/blob/dev/descripcion_segmentos/descripcion_segmentos.sql
Habría que agregar,  listado_id, 'desde', listado_id, 'hasta', agg(listado_id) 'pasando por'

**Comment by hernan-alperin** [comment]
Según la propuesta de arriba
tendríamos todos los registros del listado
el primero, el último y un array con el resto

x otro lado, otra propuesta
pego lo de Telegram:
¿`cuál sería la nueva estructura a diferencia de segmento_id | mza  | lado |  descripcion` actual?

`segmento_id | que_onda (desde/hasta/pasando por)  | mza | lado | descripcion (¿qué cambia?)| listado_id (Null si pasa por todo el lado)` 
podría ser una idea..
