### ISSUE TITLE
sacar harcodeado de conexion

### ISSUE THREAD

**Issue by hernan-alperin** [hernan-alperin/Segmentacion-CORE#3]
lo hiciste vos? si no, dónde tengo que hacerlo?
estoy perdido entre repos y comits y branches

**Comment by hernan-alperin** [comment]
Dónde se hizo o hay que hacerlo?

**Comment by manureta** [comment]
mira el pull request... eso es lo que hice.

**Comment by hernan-alperin** [comment]
hecho en dev
