### ISSUE TITLE
SQLSTATE[42601]: Syntax error: 7 ERROR: error de sintaxis en o cerca de «order»

### ISSUE THREAD

**Issue by manureta** [hernan-alperin/Segmentacion-CORE#34]
https://github.com/hernan-alperin/Segmentacion-CORE/blob/636e3847f47d21f8b35b87138d182fe5df9c85f0/manzanas_independientes/segmentar_listado_equilibrado.sql#L58

**Comment by hernan-alperin** [comment]
una coma extra al final de la linea anterior
