### ISSUE TITLE
Error con algun integer vacio en funcion describe_segmentos_con_direcciones

### ISSUE THREAD

**Issue by manureta** [hernan-alperin/Segmentacion-CORE#36]
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: la sintaxis de entrada no es válida para tipo integer: «» CONTEXT: función PL/pgSQL indec.describe_segmentos_con_direcciones(text) en la línea 4 en RETURN QUERY (SQL: SELECT segmento_id, lpad(frac::text,2,'0') frac, lpad(radio::text,2,'0') radio, viviendas vivs, descripcion detalle, lpad(seg,2,'0') seg, null ts FROM indec.describe_segmentos_con_direcciones('e1241') order by frac,radio,segmento_id LIMIT 1000;)

CASO e1241 en arsappdev

**Comment by hernan-alperin** [comment]
REGEXP_REPLACE(COALESCE(<column>::character varying, '0'), '[^0-9]*' ,'0')::integer

**Comment by manureta** [comment]
continua el error
