### ISSUE TITLE
function describe_segmentos general para el esquema

### ISSUE THREAD

**Issue by hernan-alperin** [hernan-alperin/Segmentacion-CORE#52]
juntar todos los describe_segmentos_con_direcciones_ffrr(esquema, frac, radio)
con todos los radios que aparecen en el listado
en una tabla esquema.r3
cada vez que se segmenta actualiza esa tabla
y indec.describe_segmentos_con_direcciones(esquema)

**Comment by manureta** [comment]
Generar función que actualice r3 del esquema:
indec.sincro_r3_ffrr(esquema,frac,radio)
llamando a 
update esquema.r3 con la salida de
describe_segmentos_con_direcciones_ffrr(esquema, frac, radio)

**Comment by hernan-alperin** [comment]
crear esquema.r3 con una salida nula de describe_segmentos_con_direcciones_ffrr(esquema, frac, radio)
y con aceptar corre update

**Comment by hernan-alperin** [comment]
https://github.com/hernan-alperin/Segmentacion-CORE/blob/dev/descripcion_segmentos/syncro_r3_ffrr.sql

**Comment by manureta** [comment]
Falta pushear ?

**Comment by hernan-alperin** [comment]
está listo en la rama r3
https://github.com/hernan-alperin/Segmentacion-CORE/blob/r3/descripcion_segmentos/describe_segmentos_con_direcciones.sql
