### ISSUE TITLE
Error al generar descripción de colectivas con algún string  en null. 

### ISSUE THREAD

**Issue by manureta** [hernan-alperin/Segmentacion-CORE#65]
SQLSTATE[22004]: Null value not allowed: 7 ERROR:  query string argument of EXECUTE is null
CONTEXT:  PL/pgSQL function indec.descripcion_colectiva(text,integer) line 35 at EXECUTE

**Comment by hernan-alperin** [comment]
```
  execute '
  select case when cod_subt_v != ''CO10''
    then nombre
    else ''vivienda colectiva''
  end
  from "' || esquema || '".listado
  join public.subtipo_vivienda st
  on cod_subt_v = st.codigo
  where ' || listado_id || ' = listado.id
  ' into subtipo;
```
parece que `esquema` o `listado_id` es Null ... qué proceso llama a esta función en qué radio?

**Comment by manureta** [comment]
Esta función se llama desde la sincro r3 ...
busco el caso testigo, caundo lo vea lo agrego.

Será cod_subt_v que es null ?

**Comment by hernan-alperin** [comment]
me parece que no:
```
execute
'SELECT EXISTS (SELECT 1
  FROM information_schema.columns
  WHERE table_schema=''' || esquema || ''' AND table_name=''listado'' AND column_name= ''cod_subt_v'')
' into hay_subtipo;

IF (hay_subtipo) THEN
  execute '
  select not (cod_subt_v = '''' or cod_subt_v is Null)
    from "' || esquema || '".listado where id = ' || listado_id || '
' into hay_subtipo;
END IF;

IF (hay_subtipo) THEN 
...
```
pero puede ser que la lógica este mal, podemos ver si es el caso? 
o le pongo un coalesce() o lo salvo con un or _ is Null sin más?
