### ISSUE TITLE
filtrar o marcar listado para usar los 2 diferentes algoritmos

### ISSUE THREAD

**Issue by hernan-alperin** [hernan-alperin/Segmentacion-CORE#8]
function indec.dividir_listado(aglomerado, cant_vivs)

genera 2 sublistados
uno para cada algoritmo
aglomerado.listado_recorrido
aglomerado.listado_lados_completos

cant_viviendas usa cargar_conteos
que usa contar_vivienda donde están definidos los códigos que cuentan

**Comment by hernan-alperin** [comment]
en qué orden ejecutar las funciones)

lados_adyacentes debe excluir los lados que SI están en listado_recorrido
(si no, los incluiría con 0 vivs... o ver cómo está el listado en C1 (?1)
hacer una view lados_completos_adyacentes
de lados_adyacentes que excluya los lados a considerar para recorridos
(?2)

**Comment by hernan-alperin** [comment]
que la function no sea procedural sino que 
devuelva el listado con una columna que refiera a qué método debe usar

parámetro extra si queremos filtar por método

**Comment by hernan-alperin** [comment]
la estructura de la tabla listado no puede cambiar porque hay que declararla en la function plpgsql

**Comment by manureta** [comment]
La estructura de la tabla de salida podría ser..
(id_listado, tipo_listado)
no se si falta algo más que salga de esta función (?)

**Comment by hernan-alperin** [comment]
sí,
(id_listado, metodo_de_segmentar)

**Comment by hernan-alperin** [comment]
https://github.com/hernan-alperin/Segmentacion-CORE/blob/filtrar_listado/filtrar_listado.sql

**Comment by hernan-alperin** [comment]
hay que cambiar en DAO.py
get_listado(region)
linea 61

y en manzanas_independientes.sql
linea 29

invocando a la funcion filtrar_listado

**Comment by hernan-alperin** [comment]
se usa directamente el mixto en secuencia. primero por lado y luego por listado usando function lados_excedidos
